# Fragment Pair - Fragment Derivative Matching

Having good / robust datasets to test and benchmark the scorting functions is paramount, to this regard, a number of curated datasets will be prepared and refined. This may also form the basis for a more rigorous dataset in the future.

### Imports

In [52]:
import pandas as pd
import numpy as np

### First pass preparation

Working with the full dataset, we will simply group all fragments by their association to derivatives. This is arbitrary and mostly to get familiar with the data. Filters will need to be subsequently applied.

In [53]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')
grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)

# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
# result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_paired_all.csv', index=False)
# result_df.head(5)

In [54]:
result_df.shape

(41, 111)

In [55]:
# result['Fragment Name'][0]

### Focused Sets

In [56]:
df.columns

Index(['Derivative ID', 'Fragment ID', 'Derivative Name', 'Fragment Name',
       'Derivative Crystal', 'Fragment Crystal', 'Derivative Observation',
       'Fragment Observation', 'SuCOS Average Score', 'SuCOS Feature Score',
       'SuCOS Volume Score', 'Num Recapitulated Inspiration Features',
       'Recapitulated Inspiration Feature Fraction',
       'Num Shared Protein Interactions', 'Max Eyeball'],
      dtype='object')

#### Max's selections

In [57]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')

# Fiter by Max's assessment of the structures
df = df[df['Max Eyeball'] == "YES"]

grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Filter out rows where the list is empty
result = result[result['Fragment Name'].astype(bool)].reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)

# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_max_yes.csv', index=False)
result_df.head(5)

  Derivative Name frag_name_1 frag_name_2 frag_name_3 frag_name_4
0          A2290a      A0451a         NaN         NaN         NaN
1          A2293a      A0451a         NaN         NaN         NaN
2          A2304a      A0451a         NaN         NaN         NaN
3          A2339a      A0451a         NaN         NaN         NaN
4          A2351a      A0812a      A0451a         NaN         NaN

In [58]:
result_df.shape

(37, 5)

#### Max's selections - Multi (2+)

In [59]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')

# Fiter by Max's assessment of the structures
df = df[df['Max Eyeball'] == "YES"]

grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Filter out rows where the list is empty
result = result[result['Fragment Name'].astype(bool)].reset_index()

# Filter out rows where the list is less than 2
result = result[result['Fragment Name'].map(len) >= 2].reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)
# print(result_df)
# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_max_yes_2p.csv', index=False)
result_df.head(5)

  Derivative Name frag_name_1 frag_name_2 frag_name_3 frag_name_4
0          A2351a      A0812a      A0451a         NaN         NaN
1          A2454a      A0310a      A0554a      A0884a      A0487a
2          A2629a      A0884a      A0487a         NaN         NaN
3          A2846a      A0451a      A0310a         NaN         NaN
4          A3054a      A0926a      A0387a         NaN         NaN

In [60]:
result_df.shape

(14, 5)

#### Max's selections - YES & MAYBE

In [61]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')

# Fiter by Max's assessment of the structures
df = df[df['Max Eyeball'].isin(["YES","MAYBE"])]

grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Filter out rows where the list is empty
result = result[result['Fragment Name'].astype(bool)].reset_index()

# Filter out rows where the list is less than 2
result = result[result['Fragment Name'].map(len) >= 2].reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)
# print(result_df)
# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_max_yes_mb.csv', index=False)
result_df.head(5)

,Derivative Name,frag_name_1,frag_name_2,frag_name_3,frag_name_4,frag_name_5,frag_name_6,frag_name_7
0,A1346a,A0450a,A0719a,A0387a,NaN,NaN,NaN,NaN
1,A2304a,A0501b,A0451a,A0528a,NaN,NaN,NaN,NaN
2,A2351a,A0812a,A0451a,NaN,NaN,NaN,NaN,NaN
3,A2454a,A0310a,A0554a,A0884a,A0487a,NaN,NaN,NaN
4,A2629a,A0884a,A0487a,A0922a,A0528a,A0501b,NaN,NaN

### SucOS AVG - YES/MAYBE

In [62]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')

# Filter the DataFrame based on values in another column (e.g., level_1 > 200)
df = df[df['SuCOS Average Score'] > 0.6]

# Fiter by Max's assessment of the structures
df = df[df['Max Eyeball'].isin(["YES","MAYBE"])]

grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Filter out rows where the list is empty
result = result[result['Fragment Name'].astype(bool)].reset_index()

# Filter out rows where the list is less than 2
result = result[result['Fragment Name'].map(len) >= 2].reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)
# print(result_df)
# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_avg_max_yes_mb.csv', index=False)
result_df.head(5)

  Derivative Name frag_name_1 frag_name_2 frag_name_3
0          A2304a      A0501b      A0451a         NaN
1          A2454a      A0554a      A0884a      A0487a
2          A3221a      A1180b      A1209a      A0926a
3          A3225a      A0443a      A1180b      A0926a
4          A3324a      A0451a      A0501b         NaN

### SucOS Volume - YES/MAYBE

In [63]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')

# Filter the DataFrame based on values in another column (e.g., level_1 > 200)
df = df[df['SuCOS Volume Score'] > 0.5]

# Fiter by Max's assessment of the structures
df = df[df['Max Eyeball'].isin(["YES","MAYBE"])]

grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Filter out rows where the list is empty
result = result[result['Fragment Name'].astype(bool)].reset_index()

# Filter out rows where the list is less than 2
result = result[result['Fragment Name'].map(len) >= 2].reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)
# print(result_df)
# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_vol_max_yes_mb.csv', index=False)
print(result_df.shape)
result_df.head(5)

(28, 7)

,Derivative Name,frag_name_1,frag_name_2,frag_name_3,frag_name_4,frag_name_5,frag_name_6
0,A1346a,A0450a,A0719a,A0387a,NaN,NaN,NaN
1,A2304a,A0501b,A0451a,A0528a,NaN,NaN,NaN
2,A2351a,A0812a,A0451a,NaN,NaN,NaN,NaN
3,A2454a,A0310a,A0554a,A0884a,A0487a,NaN,NaN
4,A2629a,A0884a,A0487a,A0922a,A0528a,A0501b,NaN

### SucOS Colour - YES/MAYBE

In [64]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')

# Filter the DataFrame based on values in another column (e.g., level_1 > 200)
df = df[df['SuCOS Feature Score'] > 0.45]

# Fiter by Max's assessment of the structures
df = df[df['Max Eyeball'].isin(["YES","MAYBE"])]

grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Filter out rows where the list is empty
result = result[result['Fragment Name'].astype(bool)].reset_index()

# Filter out rows where the list is less than 2
result = result[result['Fragment Name'].map(len) >= 2].reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)
# print(result_df)
# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
print(result_df.shape)
result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_col_max_yes_mb.csv', index=False)
result_df.head(5)

(4, 4)

  Derivative Name frag_name_1 frag_name_2 frag_name_3
0          A2454a      A0554a      A0884a      A0487a
1          A3221a      A1180b      A1209a      A0926a
2          A3225a      A0443a      A1180b      A0926a
3          A3324a      A0451a      A0501b         NaN

### SucOS Volume

In [65]:
df = pd.read_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/max_A71EV2A_sucos.csv')

# Filter the DataFrame based on values in another column (e.g., level_1 > 200)
df = df[df['SuCOS Volume Score'] > 0.85]

grouped = df.groupby('Derivative Name')['Fragment Name'].apply(lambda x: x).reset_index()

# Group by 'Derivative Name' and combine 'Fragment Name' into a single row
result = grouped.groupby('Derivative Name')['Fragment Name'].apply(list).reset_index()

# Filter out rows where the list is empty
result = result[result['Fragment Name'].astype(bool)].reset_index()

# Filter out rows where the list is less than 2
result = result[result['Fragment Name'].map(len) >= 2].reset_index()

# Exploding the list into separate columns
result_list_exp = pd.DataFrame(result['Fragment Name'].tolist())

# Setting column names for the new DataFrame
result_list_exp.columns = [f'frag_name_{i+1}' for i in range(result_list_exp.shape[1])]

# Joining the new DataFrame with the original ID column
result_df = result[['Derivative Name']].join(result_list_exp)
# print(result_df)
# Replace any None with NaN if desired (optional, as pandas automatically uses NaN for missing numerical data)
result_df.fillna(value=np.nan, inplace=True)

# Write to csv
print(result_df.shape)
result_df.to_csv('/Users/nfo24278/Documents/dphil/targets/A71EV2A/derivative_matching/A71EV2A_sucos_vol.csv', index=False)
result_df.head(33)

(25, 6)

   Derivative Name frag_name_1 frag_name_2 frag_name_3 frag_name_4 frag_name_5
0           A1346a      A1180b      A1169a      A1148a         NaN         NaN
1           A2290a      A0451a      A1148a      A0487a      A1180b         NaN
2           A2293a      A0501b      A1148a      A1180b      A0487a         NaN
3           A2339a      A1169a      A1180b      A1209a      A1148a         NaN
4           A2846a      A0451a      A1169a      A1180b      A1209a      A1148a
5           A2972a      A1148a      A1169a      A1180b         NaN         NaN
6           A3054a      A1148a      A1180b         NaN         NaN         NaN
7           A3066a      A0451a      A1148a      A0487a      A1180b         NaN
8           A3175a      A1180b      A1209a      A1148a      A1169a         NaN
9           A3177a      A1169a      A1148a      A1180b         NaN         NaN
10          A3181a      A0451a      A1169a      A1180b      A1209a      A1148a
11          A3186a      A1169a      A1148a         NaN         NaN         NaN
12          A3189a      A1169a      A1180b      A1209a      A1148a         NaN
13          A3191a      A1169a      A1209a      A1180b      A1148a         NaN
14          A3194a      A1180b      A1148a         NaN         NaN         NaN
15          A3210a      A1169a      A1180b      A1148a         NaN         NaN
16          A3229a      A1169a      A1148a      A1180b         NaN         NaN
17          A3234a      A1148a      A1180b         NaN         NaN         NaN
18          A3264a      A1169a      A1180b      A1209a      A1148a         NaN
19          A3279a      A1148a      A1180b         NaN         NaN         NaN
20          A3280a      A1169a      A1209a      A1180b      A1148a         NaN
21          A3286a      A1169a      A1180b      A1209a      A1148a         NaN
22          A3305a      A0487a      A1148a         NaN         NaN         NaN
23          A3306a      A1169a      A1209a      A1180b      A1148a         NaN
24          A3324a      A0501b      A1148a      A1180b         NaN         NaN